### ISSUE TITLE
对1.20.6的支持

### ISSUE THREAD

**Issue by Hikari16665** [haiman233/HaimanTech2#13]
如题，添加对1.20.6的支持

**Comment by Hikari16665** [comment]
个人服务器测试后已解决
已发PR https://github.com/haiman233/HaimanTech2/pull/14/files

**Comment by haiman233** [comment]
1.20.6我目前是打算在rsc版本支持

**Comment by haiman233** [comment]
可以创建一个新的文件夹，然后把适配1.20.6的配置放进去

**Comment by haiman233** [comment]
因为目前服务器大多还是1.19-1.20

**Comment by Hikari16665** [comment]
pr https://github.com/haiman233/HaimanTech2/pull/15

**Comment by haiman233** [comment]
> pr #15

你这也不是rsc啊

**Comment by haiman233** [comment]
先放这吧，我自己来搞

**Comment by haiman233** [comment]
正式版1.0.1版本已完成
