### ISSUE TITLE
recipe的数字重复

### ISSUE THREAD

**Issue by balugaq** [haiman233/HaimanTech2#2]
# machines.yml

生物献祭机( HAIMAN_FOXY_PRODUCER )的最后两个配方都是9（如下）
    '9':
      speed-in-seconds: 180
      input:
        '1':
          type: SLIMEFUN
          id: CELESTIAL_SWORD
          amount: 1
        '2':
          type: NONE
          id: N/A
          amount: 1
      output:
        '1':
          type: SLIMEFUN
          id: CELESTIAL_SWORD
          amount: 1
        '2':
          type: SLIMEFUN
          id: CELESTIAL_SHARD
          amount: 1
    '9':
      speed-in-seconds: 180
      input:
        '1':
          type: SLIMEFUN
          id: CURSED_SWORD
          amount: 1
        '2':
          type: NONE
          id: N/A
          amount: 1
      output:
        '1':
          type: SLIMEFUN
          id: CURSED_SWORD
          amount: 1
        '2':
          type: SLIMEFUN
          id: CURSED_SHARD
          amount: 1

**Comment by balugaq** [comment]
emm，发出来之后缩进没了，问题不大

**Comment by haiman233** [comment]
欧了
